---
title: "Visualising Male and Female Representation in Text"
author: "Cara Thompson"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Welcome!

This is the Github Repo for my [Visualising Male and Female Representation in Text Shiny app](https://cararthompson.shinyapps.io/VisualisingMFRepresentation/). It's here to make the code available to others, as well as to help keep track of issues, bug reports and feature requests. 

## What does the app do? 

This app analyses the text users enter in the side panel and produces three sets of graphs.

* The first set of graphs focuses on gender balance, showing the relative proportion of explicitly Male and Female words within each sentence, and the words used within sentences which contained predominantly Male or predominantly Female words.
* The second set presents a Sentiment analyis, showing the different emotions detected in the text and the evolution of positive and negative emotions throughout the text. Once again, the graphs allow users to see how the Male and Female words in their text are tied to the emotions.
* The third set presents a Topic analysis, showing the user how their words clustered together, and highlighting again where those topics were tied to words in predominantly Male or Female sentences.

The aim is not to force a perfect balance (there may be a perfectly valid reason why they have more predominantly Female sentences, for example if the main character in your text is Female). The aim is to allow writers and speakers to see the balance within their text, and take steps to redress it where necessary.

## Can we see a demo?

Sure!
 
<video controls>
<iframe width="720" height="480" src="demo/demo.mp4" align="middle" frameborder="0" allowfullscreen></iframe>
</video>

## But why?

The app was inspired by research into gender bias in preaching, and was created as a user-friendly tool for people writing speeches, sermons or other public addresses who wanted to reflect on potential biases in their texts. The graphs can all be interpreted intuitively, and are accompanied by clear explanatory text that does not require specialist knowledge. 

## What resources did you use to create it? 

* [Text Mining with R: A Tidy Approach - Julia Silge & David Robertson](https://www.tidytextmining.com/index.html)
* Categories S2.1 and S2.2 from [the USAS system - Paul Rayson](http://ucrel-api.lancaster.ac.uk/usas/tagger.html)
* The [NRC Lexicon](https://onlinelibrary.wiley.com/doi/abs/10.1111/j.1467-8640.2012.00460.x)
* The [AFINN Lexicon](https://arxiv.org/abs/1103.2903)


## Can I use it?

Of course! [Give it a go](https://cararthompson.shinyapps.io/VisualisingMFRepresentation/) and [let me know how I can improve it](https://github.com/cararthompson/VisualisingMFRepresentation/issues)!

If you find the app useful for your own purposes, please reference it in your own work. 